projects:
  Jobs API:
    schemaPath: src/graphql/schema.json
    includes:
      - grapql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: types/API.ts
        docsFilePath: grapql
        region: us-east-1
        apiId: zhe3rrjco5fhthwc2rif3hky7u
        maxDepth: 2
extensions:
  amplify:
    version: 3
